#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo -e "\e[1;31mThis program must be run as root" 
   exit 1
fi
echo "*********************************"
echo "*  Baking System UX for you...  *"
echo "*********************************"
echo "Target:d11"
echo ""

echo "Installing Base System..." 
#Default Config for d11
cp -f /usr/src/UX/SRC/special/d11/etc/system-ux /etc/system-ux
#Base System
bash /usr/src/UX/scripts/platform_agnostic

#Install sudo 
apt -y install sudo
#Change administrator user to admin and give sudo rights
usermod -l admin administrator
usermod -aG sudo admin

#Change name in Grub
sed -c -i "s/\(GRUB_DISTRIBUTOR *= *\).*/\1'System UX'/" /etc/default/grub

#Run Release script
bash /usr/src/UX/scripts/relselector

echo "Bake Finished"