#!/bin/sh
{ echo "\033[1;36m	Mier Engineering \033[1;34mSystem \033[1;32mU\033[1;34mX V"; cat /etc/ux-version ; } | tr "\n" "."
echo " \033[1;32m"
echo ""
echo "Kernel:"
uname -rm
echo " \033[1;0m"
Echo "Mier Engineering UX	Unified Operating System"
Echo "	Copyright (c) 2022 Angel Mier"