#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo -e "\e[1;31mThis program must be run as root" 
   exit 1
fi
echo "*********************************"
echo "*  Baking System UX for you...  *"
echo "*********************************"
echo "Target:p8"
echo ""

echo "Installing Base System..." 
#Default Config for p8
cd /usr/src/
git clone https://github.com/foundObjects/pve-nag-buster.git
bash /usr/src/pve-nag-buster/install.sh
cp -r -f /usr/src/UX//special/p8/etc/* /etc/
cp -r -f /usr/src/UX//special/p8/usr/bin/* /usr/bin/
cp -r -f /usr/src/UX//special/p8/usr/share/* /usr/share/
mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.disabled
mv /etc/apt/sources.list.d/ceph.list /etc/apt/sources.list.d/ceph.disabled
apt update
apt -y full-upgrade

#Splash Screen
cp -f /usr/src/UX/res/logo/uxsplash.png /etc/uxsplash.png
#Base System
bash /usr/src/UX/scripts/platform_agnostic

#Enable splash service
if [ $(systemctl is-enabled system-ux.splash.service) != "enabled" ]; then
chmod 644 /etc/systemd/system/system-ux.splash.service
systemctl daemon-reload
systemctl enable system-ux.splash.service
fi

#Install sudo 
apt -y install sudo
#Create administrator user and give sudo rights (login as root needed)
echo
echo
echo
echo Adding {administrator} user, please fill the information...
adduser administrator
usermod -aG sudo administrator

#Add sbin directories to PATH
if grep -q 'export PATH=' /etc/profile;  then
  echo 'Already added sbin to path'
else
  echo 'export PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"' >> /etc/profile
fi

#Enable SSH acces as root
if grep -q ^'PermitRootLogin' /etc/ssh/sshd_config;  then
  echo 'Already PermitRootLogin'
else
  echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
fi

#Add local symbolic link to root
ln -s /var/lib/vz /local

#config shutdown and reboot without superuser
chmod 4755 /sbin/shutdown
chmod 4755 /sbin/reboot

#Run Release script
bash /usr/src/UX/scripts/relselector
cp -r -f /usr/src/UX//special/p8/etc/* /etc/

#Change name in Grub
sed -i "s/\(GRUB_DISTRIBUTOR *= *\).*/\1'System UX'/" /etc/default/grub
sed -i "s/\(GRUB_DISTRIBUTOR *= *\).*/\1'System UX'/" /etc/default/grub.d/proxmox-ve.cfg
update-grub

echo "Bake Finished"