#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo -e "\e[1;31mThis program must be run as root" 
   exit 1
fi
echo "Updating System..."
cp -rf /usr/src/UX//base/* /
chmod +x /usr/bin/uxdate
ln -sf /etc/update-motd.d/10-uname /usr/bin/version

#Default Term Program on env
if grep -q 'export TERM_PROGRAM=' /etc/environment;  then
  echo 
else
  echo 'export TERM_PROGRAM=tmux' >> /etc/environment
fi