#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo -e "\e[1;31mThis program must be run as root" 
   exit 1
fi
source /etc/system-ux

case $Release in

  rp32)
    bash /usr/src/UX/scripts/deps_rp32
    ;;

  dwsl)
    bash /usr/src/UX/scripts/deps_dwsl
    ;;

  d11)
    bash /usr/src/UX/scripts/deps_d11
    ;;

  oz2)
    bash /usr/src/UX/scripts/deps_oz2
    ;;

  *)
    echo -e "\e[1;31mUnknown release ($Release)"
    ;;
esac
